name: Docker Build

on:
  push:
    branches: ['**']  # ALL branches
    tags:
      - 'v*'
      - '*.*.*'
  workflow_dispatch:

env:
  PROJECTNAME: pkmgr

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Detect registry and token
        id: registry
        run: |
          # Auto-detect if running on Gitea/Forgejo or GitHub
          if [[ "${{ github.server_url }}" == "https://github.com" ]]; then
            echo "REGISTRY=ghcr.io" >> $GITHUB_OUTPUT
            echo "TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_OUTPUT
          else
            # Gitea/Forgejo: use server domain directly
            SERVER=$(echo "${{ github.server_url }}" | sed 's|https://||' | sed 's|http://||')
            echo "REGISTRY=${SERVER}" >> $GITHUB_OUTPUT
            # Try Gitea token first, fallback to Forgejo, then GitHub
            if [[ -n "${{ secrets.GITEA_TOKEN }}" ]]; then
              echo "TOKEN=${{ secrets.GITEA_TOKEN }}" >> $GITHUB_OUTPUT
            elif [[ -n "${{ secrets.FORGEJO_TOKEN }}" ]]; then
              echo "TOKEN=${{ secrets.FORGEJO_TOKEN }}" >> $GITHUB_OUTPUT
            else
              echo "TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_OUTPUT
            fi
          fi
          echo "IMAGE_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ steps.registry.outputs.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ steps.registry.outputs.TOKEN }}

      - name: Extract metadata and tags
        id: meta
        run: |
          REGISTRY="${{ steps.registry.outputs.REGISTRY }}"
          IMAGE="${{ steps.registry.outputs.IMAGE_NAME }}"
          COMMIT_ID=$(git rev-parse --short HEAD)
          
          TAGS=""
          if [[ "${{ github.ref }}" == refs/tags/v* ]] || [[ "${{ github.ref }}" =~ refs/tags/[0-9]+\.[0-9]+\.[0-9]+ ]]; then
            # Release tag: version, latest, YYMM, commit
            VERSION="${GITHUB_REF_NAME#v}"
            YYMM=$(date +%y%m)
            TAGS="${REGISTRY}/${IMAGE}:${VERSION}"
            TAGS="${TAGS},${REGISTRY}/${IMAGE}:latest"
            TAGS="${TAGS},${REGISTRY}/${IMAGE}:${YYMM}"
            TAGS="${TAGS},${REGISTRY}/${IMAGE}:${COMMIT_ID}"
          elif [[ "${{ github.ref }}" == refs/tags/*-beta ]]; then
            # Beta tag: beta, version-beta, commit
            VERSION="${GITHUB_REF_NAME}"
            TAGS="${REGISTRY}/${IMAGE}:beta"
            TAGS="${TAGS},${REGISTRY}/${IMAGE}:${VERSION}"
            TAGS="${TAGS},${REGISTRY}/${IMAGE}:${COMMIT_ID}"
          else
            # Any other push: devel, commit
            TAGS="${REGISTRY}/${IMAGE}:devel"
            TAGS="${TAGS},${REGISTRY}/${IMAGE}:${COMMIT_ID}"
          fi
          
          echo "TAGS=${TAGS}" >> $GITHUB_OUTPUT
          echo "COMMIT_ID=${COMMIT_ID}" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.TAGS }}
          build-args: |
            COMMIT_ID=${{ steps.meta.outputs.COMMIT_ID }}
            BUILD_DATE=${{ github.event.head_commit.timestamp }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          labels: |
            org.opencontainers.image.title=${{ env.PROJECTNAME }}
            org.opencontainers.image.description=Universal Package Manager
            org.opencontainers.image.authors=Jason Hempstead <jason@casjaysdev.pro>
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
            org.opencontainers.image.revision=${{ steps.meta.outputs.COMMIT_ID }}
            org.opencontainers.image.created=${{ github.event.head_commit.timestamp }}
