use anyhow::Result;
use clap::Command;
use clap_complete::{generate, Shell as ClapShell};
use crate::commands::Cli;
use crate::shell::ShellType;
use crate::ui::output::Output;
use std::io;

pub struct CompletionGenerator {
    shell: ShellType,
    output: Output,
}

impl CompletionGenerator {
    pub fn new(shell: ShellType, output: Output) -> Self {
        Self { shell, output }
    }

    /// Generate completion script for the shell
    pub fn generate(&self) -> Result<String> {
        let clap_shell = self.to_clap_shell()?;

        let mut app = <Cli as clap::CommandFactory>::command();
        let mut buf = Vec::new();

        generate(clap_shell, &mut app, "pkmgr", &mut buf);

        Ok(String::from_utf8(buf)?)
    }

    /// Generate custom completions with dynamic content
    pub fn generate_custom(&self) -> String {
        match self.shell {
            ShellType::Bash => self.bash_completions(),
            ShellType::Zsh => self.zsh_completions(),
            ShellType::Fish => self.fish_completions(),
            _ => self.generate().unwrap_or_default(),
        }
    }

    /// Convert our shell type to clap's shell type
    fn to_clap_shell(&self) -> Result<ClapShell> {
        match self.shell {
            ShellType::Bash => Ok(ClapShell::Bash),
            ShellType::Zsh => Ok(ClapShell::Zsh),
            ShellType::Fish => Ok(ClapShell::Fish),
            ShellType::PowerShell => Ok(ClapShell::PowerShell),
            _ => anyhow::bail!("Unsupported shell for completions: {:?}", self.shell),
        }
    }

    /// Bash completions with dynamic content
    fn bash_completions(&self) -> String {
        r#"
# pkmgr Bash Completions
# Generated by pkmgr

_pkmgr_complete_packages() {
    local cur="${COMP_WORDS[COMP_CWORD]}"
    local packages=$(pkmgr list installed 2>/dev/null | grep -E '^\s*\*' | awk '{print $2}')
    COMPREPLY=($(compgen -W "$packages" -- "$cur"))
}

_pkmgr_complete_languages() {
    local languages="python node go rust ruby php java dotnet"
    COMPREPLY=($(compgen -W "$languages" -- "$cur"))
}

_pkmgr_complete_repos() {
    local cur="${COMP_WORDS[COMP_CWORD]}"
    local repos=$(pkmgr repos list 2>/dev/null | grep -E '^\s*\*' | awk '{print $2}')
    COMPREPLY=($(compgen -W "$repos" -- "$cur"))
}

_pkmgr_complete_profiles() {
    local cur="${COMP_WORDS[COMP_CWORD]}"
    local profiles=$(pkmgr profile list 2>/dev/null | grep -E '^\s*\*' | awk '{print $2}')
    COMPREPLY=($(compgen -W "$profiles" -- "$cur"))
}

_pkmgr_completions() {
    local cur prev words cword
    _init_completion || return

    local commands="install remove update search list info where whatis fix node python go rust ruby php java dotnet binary iso usb repos profile config cache doctor bootstrap sync check shell"

    # Handle command aliases
    case "$prev" in
        pkmgr)
            COMPREPLY=($(compgen -W "$commands" -- "$cur"))
            ;;
        i|install)
            # Complete with available packages (this would query package manager)
            _pkmgr_complete_packages
            ;;
        r|rm|remove)
            # Complete with installed packages
            _pkmgr_complete_packages
            ;;
        u|up|update)
            # Complete with installed packages or "all"
            local packages=$(pkmgr list installed 2>/dev/null | grep -E '^\s*\*' | awk '{print $2}')
            COMPREPLY=($(compgen -W "all $packages" -- "$cur"))
            ;;
        s|search)
            # No completion for search query
            ;;
        repos)
            local subcmds="list add remove update info"
            COMPREPLY=($(compgen -W "$subcmds" -- "$cur"))
            ;;
        profile)
            local subcmds="list create use remove edit diff export import"
            COMPREPLY=($(compgen -W "$subcmds" -- "$cur"))
            ;;
        cache)
            local subcmds="list clean info refresh"
            COMPREPLY=($(compgen -W "$subcmds" -- "$cur"))
            ;;
        shell)
            local subcmds="load completions add remove env"
            COMPREPLY=($(compgen -W "$subcmds" -- "$cur"))
            ;;
        binary)
            local subcmds="search install list update remove info"
            COMPREPLY=($(compgen -W "$subcmds" -- "$cur"))
            ;;
        iso)
            local subcmds="list install remove info verify clean"
            COMPREPLY=($(compgen -W "$subcmds" -- "$cur"))
            ;;
        usb)
            local subcmds="erase write boot"
            COMPREPLY=($(compgen -W "$subcmds" -- "$cur"))
            ;;
        node|python|go|rust|ruby|php|java|dotnet)
            local subcmds="install use list remove current info search"
            COMPREPLY=($(compgen -W "$subcmds" -- "$cur"))
            ;;
    esac

    # Handle flags
    if [[ "$cur" == -* ]]; then
        local flags="--help --version --force --quiet --verbose --yes --dry-run --explain --profile --arch --global --user"
        COMPREPLY=($(compgen -W "$flags" -- "$cur"))
    fi
}

complete -F _pkmgr_completions pkmgr

# Aliases
complete -F _pkmgr_completions pki
complete -F _pkmgr_completions pkr
complete -F _pkmgr_completions pku
complete -F _pkmgr_completions pks
complete -F _pkmgr_completions pkl
"#
        .to_string()
    }

    /// Zsh completions with dynamic content
    fn zsh_completions(&self) -> String {
        r#"
#compdef pkmgr

# pkmgr Zsh Completions
# Generated by pkmgr

_pkmgr() {
    local context state line
    typeset -A opt_args

    _arguments -C \
        '(- : *)'{-h,--help}'[Show help information]' \
        '(- : *)'{-V,--version}'[Show version information]' \
        '--force[Force override safety checks]' \
        {-q,--quiet}'[Minimal output only]' \
        {-v,--verbose}'[Detailed operation output]' \
        {-y,--yes}'[Auto-confirm all prompts]' \
        '--dry-run[Show what would happen without executing]' \
        '--explain[Show underlying native commands]' \
        '--profile[Use specific configuration profile]:profile:_pkmgr_profiles' \
        '--arch[Specify target architecture]:arch:' \
        '--global[Force system-wide installation]' \
        '--user[Force user-space installation]' \
        '1:command:_pkmgr_commands' \
        '*::arg:->args'

    case $state in
        args)
            case $words[1] in
                install|i)
                    _pkmgr_available_packages
                    ;;
                remove|r|rm)
                    _pkmgr_installed_packages
                    ;;
                update|u|up)
                    _alternative \
                        'packages:installed packages:_pkmgr_installed_packages' \
                        'all:all packages:(all)'
                    ;;
                node|python|go|rust|ruby|php|java|dotnet)
                    _pkmgr_language_commands
                    ;;
                repos)
                    _pkmgr_repos_commands
                    ;;
                profile)
                    _pkmgr_profile_commands
                    ;;
                binary)
                    _pkmgr_binary_commands
                    ;;
                iso)
                    _pkmgr_iso_commands
                    ;;
                usb)
                    _pkmgr_usb_commands
                    ;;
                cache)
                    _pkmgr_cache_commands
                    ;;
                shell)
                    _pkmgr_shell_commands
                    ;;
            esac
            ;;
    esac
}

_pkmgr_commands() {
    local commands=(
        'install:Install packages'
        'i:Install packages (alias)'
        'remove:Remove packages'
        'r:Remove packages (alias)'
        'rm:Remove packages (alias)'
        'update:Update packages'
        'u:Update packages (alias)'
        'up:Update packages (alias)'
        'search:Search for packages'
        's:Search for packages (alias)'
        'list:List packages'
        'ls:List packages (alias)'
        'info:Show package information'
        'where:Show installation location'
        'whatis:Show package description'
        'fix:Fix broken dependencies'
        'node:Node.js version management'
        'python:Python version management'
        'go:Go version management'
        'rust:Rust version management'
        'ruby:Ruby version management'
        'php:PHP version management'
        'java:Java version management'
        'dotnet:.NET version management'
        'binary:Binary management'
        'iso:ISO management'
        'usb:USB management'
        'repos:Repository management'
        'profile:Profile management'
        'config:Configuration management'
        'cache:Cache management'
        'doctor:System health check'
        'bootstrap:Bootstrap system'
        'sync:Sync configuration'
        'check:Check for updates'
        'shell:Shell integration'
    )
    _describe 'command' commands
}

_pkmgr_installed_packages() {
    local packages=($(pkmgr list installed 2>/dev/null | grep -E '^\s*\*' | awk '{print $2}'))
    _describe 'installed packages' packages
}

_pkmgr_available_packages() {
    # This would query the package manager for available packages
    # For now, use common package names
    local packages=(git vim emacs curl wget gcc make python nodejs ruby go rust docker)
    _describe 'available packages' packages
}

_pkmgr_profiles() {
    local profiles=($(pkmgr profile list 2>/dev/null | grep -E '^\s*\*' | awk '{print $2}'))
    _describe 'profiles' profiles
}

_pkmgr_language_commands() {
    local commands=(
        'install:Install language version or package'
        'use:Switch active version'
        'list:Show installed versions'
        'remove:Remove language version'
        'current:Show current active version'
        'info:Show package information'
        'search:Search language-specific packages'
    )
    _describe 'language command' commands
}

_pkmgr_repos_commands() {
    local commands=(
        'list:Show configured repositories'
        'add:Add repository'
        'remove:Remove repository'
        'update:Refresh repository metadata'
        'info:Show repository information'
    )
    _describe 'repository command' commands
}

_pkmgr_profile_commands() {
    local commands=(
        'list:Show all profiles'
        'create:Create new profile'
        'use:Switch to profile'
        'remove:Delete profile'
        'edit:Edit profile'
        'diff:Compare profiles'
        'export:Export profile'
        'import:Import profile'
    )
    _describe 'profile command' commands
}

_pkmgr_binary_commands() {
    local commands=(
        'search:Search for binaries'
        'install:Install binary'
        'list:Show installed binaries'
        'update:Update binaries'
        'remove:Remove binary'
        'info:Show binary information'
    )
    _describe 'binary command' commands
}

_pkmgr_iso_commands() {
    local commands=(
        'list:Show distributions'
        'install:Download ISO'
        'remove:Delete ISO'
        'info:Show distribution info'
        'verify:Verify ISO'
        'clean:Remove old ISOs'
    )
    _describe 'iso command' commands
}

_pkmgr_usb_commands() {
    local commands=(
        'erase:Wipe USB device'
        'write:Write ISO to USB'
        'boot:Manage multi-boot USB'
    )
    _describe 'usb command' commands
}

_pkmgr_cache_commands() {
    local commands=(
        'list:Show cache contents'
        'clean:Clean caches'
        'info:Show cache usage'
        'refresh:Refresh cached data'
    )
    _describe 'cache command' commands
}

_pkmgr_shell_commands() {
    local commands=(
        'load:Load shell integration'
        'completions:Generate completions'
        'add:Add to PATH'
        'remove:Remove from PATH'
        'env:Show environment'
    )
    _describe 'shell command' commands
}

# Register completion
compdef _pkmgr pkmgr
compdef _pkmgr pki=pkmgr
compdef _pkmgr pkr=pkmgr
compdef _pkmgr pku=pkmgr
compdef _pkmgr pks=pkmgr
compdef _pkmgr pkl=pkmgr
"#
        .to_string()
    }

    /// Fish completions with dynamic content
    fn fish_completions(&self) -> String {
        r#"
# pkmgr Fish Completions
# Generated by pkmgr

# Disable file completions by default
complete -c pkmgr -f

# Global flags
complete -c pkmgr -s h -l help -d "Show help information"
complete -c pkmgr -s V -l version -d "Show version information"
complete -c pkmgr -l force -d "Force override safety checks"
complete -c pkmgr -s q -l quiet -d "Minimal output only"
complete -c pkmgr -s v -l verbose -d "Detailed operation output"
complete -c pkmgr -s y -l yes -d "Auto-confirm all prompts"
complete -c pkmgr -l dry-run -d "Show what would happen"
complete -c pkmgr -l explain -d "Show underlying commands"
complete -c pkmgr -l profile -d "Use specific profile" -xa "(pkmgr profile list 2>/dev/null | grep '^\s*\*' | awk '{print \$2}')"
complete -c pkmgr -l arch -d "Specify architecture"
complete -c pkmgr -l global -d "System-wide installation"
complete -c pkmgr -l user -d "User-space installation"

# Commands
complete -c pkmgr -n __fish_use_subcommand -a install -d "Install packages"
complete -c pkmgr -n __fish_use_subcommand -a i -d "Install (alias)"
complete -c pkmgr -n __fish_use_subcommand -a remove -d "Remove packages"
complete -c pkmgr -n __fish_use_subcommand -a r -d "Remove (alias)"
complete -c pkmgr -n __fish_use_subcommand -a rm -d "Remove (alias)"
complete -c pkmgr -n __fish_use_subcommand -a update -d "Update packages"
complete -c pkmgr -n __fish_use_subcommand -a u -d "Update (alias)"
complete -c pkmgr -n __fish_use_subcommand -a up -d "Update (alias)"
complete -c pkmgr -n __fish_use_subcommand -a search -d "Search packages"
complete -c pkmgr -n __fish_use_subcommand -a s -d "Search (alias)"
complete -c pkmgr -n __fish_use_subcommand -a list -d "List packages"
complete -c pkmgr -n __fish_use_subcommand -a ls -d "List (alias)"
complete -c pkmgr -n __fish_use_subcommand -a info -d "Package information"
complete -c pkmgr -n __fish_use_subcommand -a where -d "Installation location"
complete -c pkmgr -n __fish_use_subcommand -a whatis -d "Package description"
complete -c pkmgr -n __fish_use_subcommand -a fix -d "Fix broken dependencies"

# Language commands
complete -c pkmgr -n __fish_use_subcommand -a node -d "Node.js management"
complete -c pkmgr -n __fish_use_subcommand -a python -d "Python management"
complete -c pkmgr -n __fish_use_subcommand -a go -d "Go management"
complete -c pkmgr -n __fish_use_subcommand -a rust -d "Rust management"
complete -c pkmgr -n __fish_use_subcommand -a ruby -d "Ruby management"
complete -c pkmgr -n __fish_use_subcommand -a php -d "PHP management"
complete -c pkmgr -n __fish_use_subcommand -a java -d "Java management"
complete -c pkmgr -n __fish_use_subcommand -a dotnet -d ".NET management"

# Other commands
complete -c pkmgr -n __fish_use_subcommand -a binary -d "Binary management"
complete -c pkmgr -n __fish_use_subcommand -a iso -d "ISO management"
complete -c pkmgr -n __fish_use_subcommand -a usb -d "USB management"
complete -c pkmgr -n __fish_use_subcommand -a repos -d "Repository management"
complete -c pkmgr -n __fish_use_subcommand -a profile -d "Profile management"
complete -c pkmgr -n __fish_use_subcommand -a config -d "Configuration"
complete -c pkmgr -n __fish_use_subcommand -a cache -d "Cache management"
complete -c pkmgr -n __fish_use_subcommand -a doctor -d "System health check"
complete -c pkmgr -n __fish_use_subcommand -a bootstrap -d "Bootstrap system"
complete -c pkmgr -n __fish_use_subcommand -a sync -d "Sync configuration"
complete -c pkmgr -n __fish_use_subcommand -a check -d "Check for updates"
complete -c pkmgr -n __fish_use_subcommand -a shell -d "Shell integration"

# Subcommand completions
complete -c pkmgr -n "__fish_seen_subcommand_from install i" -xa "(pkmgr search '' 2>/dev/null | awk '{print \$1}')"
complete -c pkmgr -n "__fish_seen_subcommand_from remove r rm" -xa "(pkmgr list installed 2>/dev/null | grep '^\s*\*' | awk '{print \$2}')"
complete -c pkmgr -n "__fish_seen_subcommand_from update u up" -xa "all (pkmgr list installed 2>/dev/null | grep '^\s*\*' | awk '{print \$2}')"

# Language subcommands
for lang in node python go rust ruby php java dotnet
    complete -c pkmgr -n "__fish_seen_subcommand_from $lang; and not __fish_seen_subcommand_from install use list remove current info search" -a install -d "Install version or package"
    complete -c pkmgr -n "__fish_seen_subcommand_from $lang; and not __fish_seen_subcommand_from install use list remove current info search" -a use -d "Switch version"
    complete -c pkmgr -n "__fish_seen_subcommand_from $lang; and not __fish_seen_subcommand_from install use list remove current info search" -a list -d "Show versions"
    complete -c pkmgr -n "__fish_seen_subcommand_from $lang; and not __fish_seen_subcommand_from install use list remove current info search" -a remove -d "Remove version"
    complete -c pkmgr -n "__fish_seen_subcommand_from $lang; and not __fish_seen_subcommand_from install use list remove current info search" -a current -d "Show current"
    complete -c pkmgr -n "__fish_seen_subcommand_from $lang; and not __fish_seen_subcommand_from install use list remove current info search" -a info -d "Package info"
    complete -c pkmgr -n "__fish_seen_subcommand_from $lang; and not __fish_seen_subcommand_from install use list remove current info search" -a search -d "Search packages"
end

# Repository subcommands
complete -c pkmgr -n "__fish_seen_subcommand_from repos; and not __fish_seen_subcommand_from list add remove update info" -a list -d "Show repositories"
complete -c pkmgr -n "__fish_seen_subcommand_from repos; and not __fish_seen_subcommand_from list add remove update info" -a add -d "Add repository"
complete -c pkmgr -n "__fish_seen_subcommand_from repos; and not __fish_seen_subcommand_from list add remove update info" -a remove -d "Remove repository"
complete -c pkmgr -n "__fish_seen_subcommand_from repos; and not __fish_seen_subcommand_from list add remove update info" -a update -d "Refresh metadata"
complete -c pkmgr -n "__fish_seen_subcommand_from repos; and not __fish_seen_subcommand_from list add remove update info" -a info -d "Repository info"

# Shell subcommands
complete -c pkmgr -n "__fish_seen_subcommand_from shell; and not __fish_seen_subcommand_from load completions add remove env" -a load -d "Load integration"
complete -c pkmgr -n "__fish_seen_subcommand_from shell; and not __fish_seen_subcommand_from load completions add remove env" -a completions -d "Generate completions"
complete -c pkmgr -n "__fish_seen_subcommand_from shell; and not __fish_seen_subcommand_from load completions add remove env" -a add -d "Add to PATH"
complete -c pkmgr -n "__fish_seen_subcommand_from shell; and not __fish_seen_subcommand_from load completions add remove env" -a remove -d "Remove from PATH"
complete -c pkmgr -n "__fish_seen_subcommand_from shell; and not __fish_seen_subcommand_from load completions add remove env" -a env -d "Show environment"

# Shell type completion
complete -c pkmgr -n "__fish_seen_subcommand_from shell; and __fish_seen_subcommand_from completions" -xa "bash zsh fish powershell"
"#
        .to_string()
    }
}